### ISSUE TITLE
E-Trigger / Standby support

### ISSUE THREAD

**Issue by murmeltier08** [rancilio-pid/clevercoffee#223]
Standbyfunktion mit Timer für Display

**Comment by tbaumann** [comment]
If I may hijack this issue. What even is the E-Trigger?
I can't figure it out from the schematics at all.

Is it related to the Rancillio standby mode?

**Comment by fiendie** [comment]
@tbaumann: E-Trigger resets the 30 minute timer on Silvia E models (v5 and v6). This also happens when you start a brew or switch on hot water on an unmodified machine.

**Comment by tml89** [comment]
Whats the target? To show the E-Trigger timer in the display or implement a standbytimer (e.g. turn pid off after 30min)?

**Comment by fiendie** [comment]
That depends on whether you have a Silvia v5+ or if you do, chose to take out the CPU. 

In the former case, standby mode is just a matter of switching off the display and the heater. In the latter case you would need a separate relay to trigger the functions on the CPU.

Either way, I would stop using the word "E-Trigger" and just refer to different implementations of the standby mode.

**Comment by LoQue90** [comment]
added from @fiendie with https://github.com/rancilio-pid/clevercoffee/pull/359
