### ISSUE TITLE
Device freezes if INFLUXDB server is configured but not available

### ISSUE THREAD

**Issue by user-na** [rancilio-pid/clevercoffee#242]
Problem: Programm im ESP friert ein.

Auslöser: InfluxDB server war Aufgrund eines Stromausfalls nicht neugestartet, aber in der userconfig konfiguriert.

Hardware: ESP32

Config:
```
// INFLUXDB
#define INFLUXDB 1                 // 1 = INFLUX enabled, 0 = INFLUX disabled
#define INFLUXDB_URL "http://myinfuxdbserver:8086"            // InfluxDB server address
#define INFLUXDB_AUTH_TYPE 1       // 1 = API Token , 2 = User/Pass
#define INFLUXDB_API_TOKEN "mytoken=="
#define INFLUXDB_ORG_NAME "myorg"
#define INFLUXDB_USER ""
#define INFLUXDB_PASSWORD ""
#define INFLUXDB_DB_NAME "coffee"  // InfluxDB bucket name
#define INFLUXDB_INTERVAL 5000     // Send interval in milliseconds

```

Dies führt dazu, dass das Display nicht mehr aktualisiert wird. Vermutlich hält die Ganze Regelschleife an. Auch über den Monitor sieht man, dass er durch den fehlschlagenden Verbindungsaufbau eingefroren ist. Erst wenn die Verbindung einen timeout liefert läuft das Programm weiter, bis es zum nächsten mal an die INFLUXDB Stelle kommt. 

```
pressure raw / filterd: -1.715282 / -1.715052
[E][WiFiClient.cpp:258] connect(): socket error on fd 56, errno: 113, "Software caused connection abort"
InfluxDB write failed: connection refused
pressure raw / filterd: -1.715282 / -1.715121
[E][WiFiClient.cpp:258] connect(): socket error on fd 57, errno: 113, "Software caused connection abort"
InfluxDB write failed: connection refused
pressure raw / filterd: -1.715282 / -1.715169
[E][WiFiClient.cpp:258] connect(): socket error on fd 58, errno: 113, "Software caused connection abort"
InfluxDB write failed: connection refused
```
Schlimmstenfalls könnte es zu einer Überhitzung des Kessels kommen.

Lösungsvorschlag:

Beim booten testen ob man einen socket aufbauen kann, falls nicht InfluxDB bis zum nächsten Boot ausschalten. Den Test evtl vor jedem neuen Schreiben an den InfluxDB Server wiederholen.

**Comment by murmeltier08** [comment]
Danke für den Hinweis und die Analyse, schauen wir uns mal an!

**Comment by Squisher23** [comment]
Ich hatte das Problem in ähnlicher Weise auch schon einmal im Chat beschrieben... Scheint dann ja nicht nur bei mir aufzutreten. (https://chat.rancilio-pid.de/ranciliopid/pl/yd9ue98kii8y78oxfkf5yuxrsy) Ich habe mir mit einer Timeout-Veränderung beholfen und den Standard-Timeout von 5000ms auf 500ms verringert. Dadurch hat die Maschine zwar immer noch ein LAG, aber reagiert ausreichend schnell, um den PID sauber zu regeln und ein Kaffee brühen zu ermöglichen.

![image](https://user-images.githubusercontent.com/57119032/181306153-60b7f6a4-1314-4c3e-b4bf-52d97cdd494b.png)

**Comment by murmeltier08** [comment]
Ich habe den Fix bei mir eingerichtet mit Influx und werde es mal testen, was dann passiert.
