### ISSUE TITLE
Show WiFI SSID on display when configuration has not yet been completed

### ISSUE THREAD

**Issue by kjyv** [rancilio-pid/clevercoffee#249]
On first boot, the WiFi config needs to be set by the user but the display shows only that the PID is disabled. To prevent confusion, show a hint with the WiFi name that the user needs to connect to. E.g.
"Connect to WiFi 'CleverCoffee' to setup"

**Comment by kjyv** [comment]
Related PR #325

**Comment by fiendie** [comment]
This seems to be resolved now that #325 is merged?
