### ISSUE TITLE
Brew time is not displayed over the entire brewing process

### ISSUE THREAD

**Issue by Dual-0** [rancilio-pid/clevercoffee#280]
hey guys,

in version 3.0.1 the brew time is shown in the display only as long as the "PID BD Timer" is running. Afterwards the timer jumps back to "uptime". This only happens when Brew PID is activated.

[Settings_Screenshot](https://user-images.githubusercontent.com/37346547/201541693-677876e3-8e70-49d1-81d4-f506ba6953f3.jpg)

**Comment by murmeltier08** [comment]
I think it is fixed, when you set BD PID greater than brew time
