### ISSUE TITLE
Emergency Stop not in correct range

### ISSUE THREAD

**Issue by cottec** [rancilio-pid/clevercoffee#287]
Usable brewing temperatures are about 92-96°C. With an offset of roughly 10K, depending on machine, the set temperature can be over 100°C.
Emergency Stop should consider this!
if settemp >100 < 110 --> EmegerncyStopTemp=settemp+3
if temperature > 110 --> EmegerncyStop

Current setup:
> void testEmergencyStop() {
    if (temperature > EmergencyStopTemp && emergencyStop == false) {
        emergencyStop = true;
    } else if (temperature < 100 && emergencyStop == true) {
        emergencyStop = false;
    }
}

**Comment by murmeltier08** [comment]
i will put it in the master soon

**Comment by murmeltier08** [comment]
In the master, please check it
