### ISSUE TITLE
Temperature sensor pin on ESP32 board

### ISSUE THREAD

**Issue by JojoDevel** [rancilio-pid/clevercoffee#290]
The new ESP32 board from @fiendie uses PIN 16 (not PIN 2 anymore) for the temperature sensor. This should be noted in the `userConfig_sample.h`

**Comment by JojoDevel** [comment]
Sorry, for the merge mess. I am more used to gitlab :see_no_evil:

**Comment by LoQue90** [comment]
The new esp32 board is supposed to be use with the CleverCoffee 32 fork, not with the last release oder master in the CleverCoffee repo.
The master will in the long run not support esp32.

**Comment by JojoDevel** [comment]
Uh, my bad :see_no_evil:
