### ISSUE TITLE
Brewtimer ignores BREWSWITCHDELAY 

### ISSUE THREAD

**Issue by LoQue90** [rancilio-pid/clevercoffee#297]
If Shottimer = 0 -> Brewtimer switch back to "uptime" directly after end of Brew
BREWSWITCHDELAY in userconfig get ignored

Brewtimer should stay the time that is set in BREWSWITCHDELAY and the switch back to "uptime"

**Comment by murmeltier08** [comment]
Please check last commit: 
https://github.com/rancilio-pid/clevercoffee/commit/6bf438db3ef4d9756df68fe281ce16daa06d86a1

**Comment by LoQue90** [comment]
fix with https://github.com/rancilio-pid/clevercoffee/commit/6bf438db3ef4d9756df68fe281ce16daa06d86a1 
THX!
