### ISSUE TITLE
wifi manager und Display

### ISSUE THREAD

**Issue by murmeltier08** [rancilio-pid/clevercoffee#302]
Wifi Manager geht nur zuverlässig, wenn das Display deaktiviert ist.

**Comment by kjyv** [comment]
See #304

**Comment by murmeltier08** [comment]
Idea: Use flag to identify if wifi setup was done.

**Comment by murmeltier08** [comment]
Tested in PR #340

**Comment by LoQue90** [comment]
closed with #405
