### ISSUE TITLE
PIN Mapping and platform ini to ignore list? 

### ISSUE THREAD

**Issue by murmeltier08** [rancilio-pid/clevercoffee#328]
PIN Mapping and platform ini to ignore list like src/userConfig.h ?

**Comment by fiendie** [comment]
Why? They're supposed to be the same for everyone. 
We added the platformio_extra.ini line for user-defined settings. 

What is adding pinmapping.h to the ignore list going to accomplish?
The whole point was having a fixed pin mapping in the first place.
