### ISSUE TITLE
PR 325 - no display not working

### ISSUE THREAD

**Issue by murmeltier08** [rancilio-pid/clevercoffee#337]
No build with disable display

Liegt daran, dass ich kein display Nutze und daher ```displayLogo(String("Version "), String(sysVersion))``` in Zeile 1885 kracht (https://github.com/rancilio-pid/clevercoffee/commit/56cda4317ba0464e7a1e694ca91a247b9340956d#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2R1885)

**Comment by tml89** [comment]
Same for: 
https://github.com/rancilio-pid/clevercoffee/commit/56cda4317ba0464e7a1e694ca91a247b9340956d#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2R1358
