### ISSUE TITLE
Some issues with DS18B20 + IP address on the screen

### ISSUE THREAD

**Issue by subcarpathia** [rancilio-pid/clevercoffee#343]
Hello

During compiling with DS18B20 sensor - found some issues

When set in userConfig.h
`#define TEMPSENSOR 1`

Causes compilation error:
Solution

In main.cpp

1. Add #include <OneWire.h> before DallasTemperature
2. Remove IF loop for #include <DallasTemperature.h> - 
3. Line 290
// Dallas temp sensor

OneWire oneWire(PIN_TEMPSENSOR);         // Setup a OneWire instance to communicate with OneWire
DallasTemperature sensors(&oneWire);

// #if TEMPSENSOR == 1
//     OneWire oneWire(PINTEMPSENSOR);         // Setup a OneWire instance to communicate with OneWire
//                                             // devices (not just Maxim/Dallas temperature ICs)
//     DallasTemperature sensors(&oneWire);
//     DeviceAddress sensorDeviceAddress;      // arrays to hold device address
// #endif

4. Line 1972

// Dallas temp sensor
    #if TEMPSENSOR == 1
        sensors.begin();
        // sensors.getAddress(sensorDeviceAddress, 0); 
        // sensors.setResolution(sensorDeviceAddress, 10);
        sensors.requestTemperatures();
        temperature = sensors.getTempCByIndex(0);
    #endif

5. Line 1416

const char sysVersion[] = (STR(FW_VERSION) "." STR(FW_SUBVERSION) "." STR(FW_HOTFIX) " " FW_BRANCH " " AUTO_VERSION);

changed to 

const char sysVersion[] = (STR(FW_VERSION) "." STR(FW_SUBVERSION) "." STR(FW_HOTFIX) " " FW_BRANCH " ");

6.
After run :

    default is PID off manually - when enter on the webpage - it shows the PID is on - when I switch OFF then PID is on
    default values for temperature is 20 and for brewing times is 0

**Will be very , very nice to show for about 1-2 seconds assigned the IP address after login to WiFi . Makes things much easier when address is assigned dynamically,**

**Comment by LoQue90** [comment]
i just downloaded the newest master-esp8266, change tempsensor in userconfig to 1 und build just fine.
I´m pretty sure you used a newer version with an old userconfig.
For 6.
sounds like you came from an old release (2,X), erase flash and reupload in total fill fix that.
