### ISSUE TITLE
MQTT not working after several hours 

### ISSUE THREAD

**Issue by locolc** [rancilio-pid/clevercoffee#345]
Im running 3.1.2 full fersion without scale and without TOF. Influx not active. the issue i have is that i see mqtt not working anymore after one night if continuously been active. any help?

**Comment by aweens** [comment]
I also have an always-on setup and had the same issue. 
For some reason mqtt loses connection to the server and has to reconnect every now and then. 
However there's a limit for number of reconnects. MQTT is also using maxWifiReconnects, which is by default set to 5.
So after 5 reconnects it doesn't even attempt to connect anymore.

I solved the problem by reseting the reconnect counter when there was a successful connection attempt.

In checkMQTT() add MQTTReCnctCount = 0 like this:

if (mqtt.connect(hostname, mqtt_username, mqtt_password, topic_will, 0, true, "offline") == true) {
   **MQTTReCnctCount = 0;**  
   mqtt.subscribe(topic_set);
...

**Comment by locolc** [comment]
Hi there thanks for the Reply! i will try with that one.

**Comment by murmeltier08** [comment]
@kjyv should we add this to a PR?
