### ISSUE TITLE
PINMAPPING for Pressuresensor

### ISSUE THREAD

**Issue by JonasB2602** [rancilio-pid/clevercoffee#364]
https://github.com/rancilio-pid/clevercoffee/blob/b30a0fe36d6c7c6007f436eb1dd3ea3e83da2826/src/pinmapping.h#L25

#define PIN_PRESSURESENSOR 23 shall be 36

**Comment by LoQue90** [comment]
already open pr for #362

**Comment by LoQue90** [comment]
fixed in #362 
can be closed.
