### ISSUE TITLE
Inonsistent Brew switch behaviour - likely debounce missing

### ISSUE THREAD

**Issue by genkigenki** [rancilio-pid/clevercoffee#413]
This code block has no function:

            if ((millis() - lastDebounceTimeBrewTrigger) > debounceDelayBrewTrigger) {
                // whatever the reading is at, it's been there for longer than the debounce
                // delay, so take it as the actual current state:

                // if the button state has changed:
                if (reading != buttonStateBrewTrigger) {
                    buttonStateBrewTrigger = reading;
                }
            }

as buttonStateBrewTrigger is not used anywhere else.
--> Brewswitchtrigger is not debounced.

This leads to issues in my machine.
Also the 5s delay was likely is introduced due to these issues ("Prellen")
Remove that as well

https://github.com/rancilio-pid/clevercoffee/assets/3080081/d1834d7d-1d32-4769-bb84-85508d9e67f9

**Comment by LoQue90** [comment]
https://github.com/rancilio-pid/clevercoffee/pull/430
