### ISSUE TITLE
Erratic behaviour of "Steam" switch when configured as push button

### ISSUE THREAD

**Issue by genkigenki** [rancilio-pid/clevercoffee#416]
Steam switch (in push button configuration) sometimes switches off by itself.

In main wird jeden looppid() aufgerufen (ohne debounce!):

void checkSteamON() {
[...] 
    // check digital GIPO
    if (digitalRead(PIN_STEAMSWITCH) == HIGH) {
        steamON = 1;
    }

und zusätzlich später jeden LOOP aus steamswitchvoid.h (mit debounce):

void checkSteamSwitch() {
[...]
        int reading = digitalRead(PIN_STEAMSWITCH);
[...]                        steamON = 1;

**Comment by LoQue90** [comment]
https://github.com/rancilio-pid/clevercoffee/pull/430
