### ISSUE TITLE
Steam Mode does not exit on Quickmill (Thermoblock) machines with PID only+

### ISSUE THREAD

**Issue by FloR012** [rancilio-pid/clevercoffee#466]
On my Quickmill with PID only+ (optocoupler board listed in manual) the brew detection works. When the steam mode is activated by the steam switch (default hardware), the pump starts pulsing and the software detects steam mode. This is shown in the display and the setting temperature is set to 120°C. The problem is, that this mode will never exit again. The only way to get around this is to switch off the machine and wait for the temperature to lower belwo the desired value for coffee.

**Comment by FloR012** [comment]
Hi,
i made some verbose logs, one with the steam mode on v3.2 and one with the steammode on v4.0, please find them atteched here.
From my understanding, on v3.2 the machine state changes from "steam mode" to "cooldown" when the steam switch is switched off. On v4.0 an cannot see the transition to "cooldown", machine state stays on "steam" forever. The logfiles are quite large, as I waited for the temperature to cool down far below the setting value (~73°C).

[output_3_2.txt](https://github.com/rancilio-pid/clevercoffee/files/14539008/output_3_2.txt)
[output_v4_0.txt](https://github.com/rancilio-pid/clevercoffee/files/14539014/output_v4_0.txt)

**Comment by LoQue90** [comment]
please give this a try:
https://github.com/rancilio-pid/clevercoffee/commit/18c270f55df07b0f759716d4c8aa4d9b589592b6

**Comment by LoQue90** [comment]
Steam mode detection over pumpe pulses will be removed soon, its not very reliant.
