### ISSUE TITLE
Kein zweiter Bezug möglich bei Verwendung von BREWCONTROL_TYPE = 2

### ISSUE THREAD

**Issue by philkhn** [rancilio-pid/clevercoffee#507]
Bei Verwendung des aktuellen Masters zusammen mit einer verbauten Waage ist es nicht möglich einen zweiten Bezug zu starten. Der BREWSWITCH_TYPE ist MOMENTARY. 
Nach dem Aus- und wieder Einschalten der Maschine ist ein erneuter Bezug Möglich. Meine config.h habe ich mal als .txt angehängt. 
 
[userConfig.txt](https://github.com/rancilio-pid/clevercoffee/files/15458856/userConfig.txt)

**Comment by LoQue90** [comment]
@FabianSperrle didn't you already finde the problem?

**Comment by LoQue90** [comment]
@philkhn 
ist ein bekannter bug, ist hoffentlich die nächsten Tage raus :)

**Comment by LoQue90** [comment]
should be fixed with #496
