### ISSUE TITLE
If Temp error happens during shot, shot is not stopped 

### ISSUE THREAD

**Issue by murmeltier08** [rancilio-pid/clevercoffee#60]
Wenn beim Bezug der Temp. sensor Error kommt, Bezug wird nicht beendet.

**Comment by kjyv** [comment]
Is this about the brew counter or the automatic pump control?

**Comment by murmeltier08** [comment]
It was one observation of one guy. He say that the pump do not stop if you get a sensor error during the brewing. 
We can close this issue, it happened not again.
