### ISSUE TITLE
Offlineanzeige, TOF

### ISSUE THREAD

**Issue by murmeltier08** [rancilio-pid/clevercoffee#97]
„Offlinemodus“ kollidiert aktuell mit der füllstandsanzeige, vllt etwas nach links rücken oder durch „offline“ ersetzen.
![image](https://user-images.githubusercontent.com/44034211/113555967-0a2dc100-95fc-11eb-89af-457ec23595a8.png)

**Comment by kjyv** [comment]
Changed it to offline in #275
